apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  ports:
  - port: 8888
    nodePort: 32002
    protocol: TCP
  selector:
    app: webapp
  type: NodePort
